### ISSUE TITLE
USB port shows up but fails to connect sayign serial address already in use

### ISSUE THREAD

**Issue by nabeelmoeen** [schuhumi/Termux_CDC_ACM#1]
I'm using Mi MIx 2 (chiron) running LineageOS 17. 
after following the setup instructions and verifying the printer is detected when plugged in via OTG-USB, I get the below error when attempting to connect via Octoprint;

`"Changing monitoring state from "Error: Connection error, see Terminal tab" to "Offline (Error: Connection error, see Terminal tab)" Unexpected error while connecting to serial port /dev/bus/usb/001/002, baudrate 115200 from hook Termux_CDC_ACM: OSError: '[Errno 98] Address already in use' @ comm.py:_open_serial:2781"`

**Comment by schuhumi** [comment]
This was artifact of serial_printer's instanciation freezing, due to it waiting forever for serialDaemon to connect to the socket, which didn't happen in case the daemon failed somehow. Now there's a connection timeout in place
