### ISSUE TITLE
pip failed with a missing libexpat.so.1

### ISSUE THREAD

**Issue by aavogt** [schuhumi/Termux_CDC_ACM#3]
Please add `pkg install libexpat` to step 2 of the readme.

**Comment by schuhumi** [comment]
Thank you for the hint! I just added it without checking myself, because I migrated away from Octoprint. If you are actively using this plugin and would like to work on it, I can also share the repository with you :)

**Comment by schuhumi** [comment]
Thank you for the hint! I just added it without checking myself, because I migrated away from Octoprint. If you are actively using this plugin and would like to work on it, I can also share the repository with you :)

**Comment by aavogt** [comment]
What do you use instead of octoprint?

**Comment by schuhumi** [comment]
Well I migrated to klipper+mainsail. Mainly because I didn't want to keep recompiling Marlin for every config change all the time. Also klipper can use multiple mainboards as stepper drivers simultaneously, which came in handy for me.
